spring.application.name=project
# serveur
server.port=8080
# jsp
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# database pja
database.connection.host=mysql
database.connection.port=3306
database.connection.username=myuser
database.connection.password=mypassword
database.connection.database=myapp_db

